# Generated by Django 4.1.2 on 2022-10-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channel0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=2022, max_length=254),
            preserve_default=False,
        ),
    ]
