# Generated by Django 4.1.2 on 2022-10-21 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channel0', '0002_student_email_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='None', max_length=20, null=True)),
                ('profile_pic', models.ImageField(default='profile.png', null=True, upload_to='')),
                ('police_number', models.IntegerField(null=True)),
                ('rank', models.CharField(max_length=20)),
                ('telephone', models.IntegerField(null=True)),
                ('position', models.CharField(blank=True, choices=[(' OIC', 'OIC'), ('CI', 'CI'), ('Academic staff', 'Academic staff'), ('IO', 'IO')], default='None', max_length=20, null=True)),
                ('registration_date', models.DateTimeField(default=datetime.datetime.now)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
    ]
