# Generated by Django 4.1.2 on 2022-10-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Channel0', '0003_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_desc', models.TextField()),
                ('sub_date', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('leader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to='Channel0.leader')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='Channel0.student')),
            ],
        ),
    ]
