# Generated by Django 4.1.2 on 2022-10-21 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Channel0', '0004_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annoucement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annoucementTitle', models.CharField(max_length=100)),
                ('anouncement_desc', models.TextField()),
                ('announceDesc', models.DateTimeField(default=datetime.datetime.now)),
                ('leader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_id', to='Channel0.leader')),
            ],
        ),
    ]
