# Generated by Django 4.1.2 on 2022-10-21 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Channel0', '0005_annoucement'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_id', models.CharField(max_length=200)),
                ('student_id', models.CharField(default='ICT', max_length=200)),
                ('desc', models.TextField()),
                ('commentTime', models.DateTimeField(default=datetime.datetime.now)),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_id', to='Channel0.issue')),
            ],
        ),
    ]
